import type { Destination } from './types'

export const DESTINATIONS: Destination[] = [
  {
    id: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    emoji: '🗼',
    primary: '#dc2626',
    secondary: '#fce7e7',
    accent: '#1e1b4b',
    pattern: 'waves',
    milesRequired: 0,
    unlocked: true,
    stampsEarned: 0,
  },
  {
    id: 'paris',
    city: 'Paris',
    country: 'France',
    emoji: '🗼',
    primary: '#1d4ed8',
    secondary: '#dbeafe',
    accent: '#fbbf24',
    pattern: 'grid',
    milesRequired: 0,
    unlocked: true,
    stampsEarned: 0,
  },
  {
    id: 'marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    emoji: '🕌',
    primary: '#db7c00',
    secondary: '#fff3d6',
    accent: '#0f6b5c',
    pattern: 'tiles',
    milesRequired: 800,
    unlocked: false,
    stampsEarned: 0,
  },
  {
    id: 'rio',
    city: 'Rio',
    country: 'Brazil',
    emoji: '🏖️',
    primary: '#16a34a',
    secondary: '#dcfce7',
    accent: '#eab308',
    pattern: 'dots',
    milesRequired: 1500,
    unlocked: false,
    stampsEarned: 0,
  },
  {
    id: 'reykjavik',
    city: 'Reykjavik',
    country: 'Iceland',
    emoji: '🏔️',
    primary: '#0e7490',
    secondary: '#cffafe',
    accent: '#e0f2fe',
    pattern: 'hex',
    milesRequired: 2500,
    unlocked: false,
    stampsEarned: 0,
  },
  {
    id: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    emoji: '🛕',
    primary: '#c026d3',
    secondary: '#fae8ff',
    accent: '#facc15',
    pattern: 'stripes',
    milesRequired: 3800,
    unlocked: false,
    stampsEarned: 0,
  },
]
